### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by bilalq** [dhleong/intellivim#34]
First off, I'd like to say this looks really cool and I'm happy to see this exists. However, I haven't been able to figure out how to get this running. Could you possibly add some installation instructions to the README?

**Comment by dhleong** [comment]
Hello, thanks for your interest! I'm not sure if it's quite ready install in production environments, but you can test it by importing the gradle project into IntelliJ and running it with the IntelliJ Plugin configuration. I haven't worked on this in a bit, but I think you can build an installable zip from the imported IntelliJ project

**Comment by dhleong** [comment]
@bilalq I've updated the project's build system to use JetBrain's new Gradle plugin, so it's pretty easy to build an installable .zip. Check out the README :)

I haven't done any other work yet, though, so it may or may not be compatible with newer versions of IntelliJ
